language: go
rvm:
  - 1.x
install:
  - true
script:
  - cd proxy && ./cibuild.sh
deploy:
  provider: script
  script:
  - cd proxy && ./cideploy.sh
  on:
    branch: master
env:
  global:
  - secure: TvD+8f7ghTa9AizKOUZzX/1r4MaHU+j4gKcjrppRPQ9qjQ9aTsYviZ+6L+2jTnh22uYtCqhyaYxk+oFGnEmVkHPZ/Ri15VIakIfvn4zFKJ6EFdSa76Fa3O4nk3zplawuKsThZ2M4C2uWzV7/iVqbtQ7WQcOMxhHzv9m4zd0/+iUvJx0G+dgzHHK3WCWKM1KZmF/2iOpjKGj2kScN8TkS9nwGfThv8vDpCCZAji4PGjFE4iTsdu73vWHCH000fg0A69+mpMzbi8+fykof5ZjRLPvvixRbvLqShg4FYGSinU5/U1gQzEg+vgKC9jUNqSidlXc5A7Qh5BBoMEGK0ujfVC50vt9WrfoKQ8sQ7EtcD35+WDXEZdr5ORcyx00JM+Kw5LU/WKDkrmJJf764A9zt7lVo3DxZLyLLb4MiXmp7N7VobKSfmPu9U0vXN1bq57DrijfSw3XbYNlq50g7wI5qoAeYiMgQ+DaHcX4WxR39rKppRLimfYcMUBJqN9HZvr57nKvihWSIRiocI27VI6hpq2uMrGm0wVs72s09obXqztOLfkjyRrcHHbc0hGwMszT1/sgtsbgdAaRAwalkrrLGdktkKKgvB94t/jyYZUv9dx1MfaKLlB+7Eplky4DoDWR+ChZrGX9w/NcKfFyf3orZVCrA413uJPiI1nJWJwuSWw0=
  - secure: aehiX+/lXdKmZtDr0rIUiz28CLl46h8J2gKx8JxjFrrABkDxGGKjrQ2U45lzocwY7XjgiSaxDsm8BaIotSfCOW0FUL0FsW1LmPzpIJP5brE3/XV8PlYXAuxyUgjVMNrtEcxFO0KTmXRv4jVPQ0eju467oEaeWCLItcfKKHSH3WphiQPgElJ7yjFKbPgjz0jRNH8jbPUtrPLPzBCWG2EKzCzYYEz0RA/hjzJ4X1L5WEmeAQYz16NwgQ/wn/ZOOeVv2N+4CluCp6Pn6M3EmrKQ05Ew6sxW9u29qgiikAB0AzT6rlpHUzxIWfAXPmRn2C++P4pPbtdLWS8DQ6P7R4NGWKhQBZtLmV6uP4NzCEND8a0cHEpPmWTdyCDCxsTqWk1f96I+AHtbjzPAkHI3LCg3AFr0tm47dv7cIWbS8fIQT04vSgdnLBtxoG8m9h4dcAJN9/fD+UzTiO5J7f9YHs/KvN9igeaAAfl2vK2sCBAhWQMcVXeuLDgI0CxnSj0+Oj98F/AP+4sO5ZCRTLbpUz+xaj4cRfyS54QuB5kG07XTNDcnfq3GzuRPDENAAukF4jDuR/k494x1lNLObYMyKW4tRZoWFsvolDlIUzt8Dnvu5J1KDpCH7OdLcovEwrDAI90eNCM9oJ/QKqwm6yMeHd59Ik9voJpgR2XGYPAvbU9AsaM=
